PORTNAME=	wdns
PORTVERSION=	0.4
CATEGORIES=	net
MASTER_SITES=	https://dl.farsightsecurity.com/dist/wdns/
MAINTAINER=	software@farsightsecurity.com
COMMENT=	low-level DNS library

USE_PKGCONFIG=	yes
GNU_CONFIGURE=	yes
USES=		pathfix gmake

.include <bsd.port.mk>
